#!/usr/bin/env node

var argv = require('optimist')
    .usage('Convert CSV file with header to JSON.\nUsage: $0')
    .demand('f')
    .alias('f', 'file')
    .describe('f', 'CSV file with header as first line')
    .argv;

var fs = require('fs');
var readline = require('readline');
var rl = readline.createInterface({
	input: fs.createReadStream(argv.file)
});

var list = [];
var processHeader = false;
var keys = [];

rl.on('line', function(line) {
  if (!processHeader) {
    processHeader = true;
    keys = line.split(/,/);
    return;
  }

  var row = {};
  var i = 0;
  var parts = line.split(/","/);
  if (parts.length == keys.length) {
    while(i < parts.length) {
      if (i == 0)
        row[keys[0]] = ltrimQuote(parts[0]);
      else if (i == keys.length-1)
        row[keys[keys.length-1]] = rtrimQuote(parts[keys.length-1]);
      else
        row[keys[i]] = parts[i];
      i++;
    }
    list.push(row);
  }
  else {
    throw new Error('Invalid line: ' + line);
  }
});

rl.on('close', function() {
  console.log(JSON.stringify(list, undefined, 2));
});

function ltrimQuote(val) {
  return val.replace(/^"/, '');
}

function rtrimQuote(val) {
  return val.replace(/"$/, '');
}
