#!/usr/bin/env node

var argv = require('optimist')
    .usage('Convert Zawgyi to Unicode.\nUsage: $0')
    .demand('f')
    .alias('f', 'file')
    .describe('f', 'Zawgyi encoded file')
    .argv;

var z2u = require('./zg12uni51');
var fs = require('fs');
var readline = require('readline');
var rl = readline.createInterface({
	input: fs.createReadStream(argv.file)
});

rl.on('line', function(line) {
  line = z2u(line);
  console.log(line);
});
