#!/usr/bin/env node
var argv = require('optimist')
    .usage('Convert Zawgyi to Unicode.\nUsage: $0')
    .demand('f')
    .alias('f', 'file')
    .describe('f', 'Zawgyi encoded file')
    .argv;

var z2u = require('./zg12uni51');
var fs = require('fs');
var readline = require('readline');
var rl = readline.createInterface({
	input: fs.createReadStream(argv.file)
});

rl.on('line', function(line) {
  line = z2u(line);
  console.log(line);
});

// var stream = fs.createReadStream(argv.file);

// var output = '';
// var line;
// stream.on('data', function(buf) {
//   line = buf.toString();
//   output += z2u(line);
//   console.log(line);
// });

// stream.on('end', function() {
//   console.log('end', output.length);
// });

// var input = 'Character Map ကုိ အသုံးၿပဳၿပီး စာလုံးထပ္မ်ား ရွာေဖြၿခင္း';
// var output = z2u(input);

// console.log('output:', output);
